---
- hosts: all
  become: true
  vars: 
     mult_packages:
          - apache2
          - php
          
  tasks: 
  - name: installing multiple mult_packages
    package: name="{{mult_packages}}" state=present
  
  - name:
    file: dest=/nagios state=directory
  
  - name:
    shell:
      cmd: cd /nagios
      cmd: wget https://sourceforge.net/projects/nagios/files/nagios-4.x/nagios-4.0.8/nagios-4.0.8.tar.gz/download
      cmd: wget https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
  